Order ID: [pnp_orderID]
Merchant ID: [pnp_order-id]
[pnp_message]

Billing Address:
[pnp_card-name]
[pnp_card-address1]
[pnp_card-address2]
[pnp_card-city], [pnp_card-state] [pnp_card-zip]

[email_shipping_begin]
Shipping Address:
[pnp_shipname]
[pnp_address1]
[pnp_address2]
[pnp_city], [pnp_state] [pnp_zip]
[email_shipping_end]

[email_purchase_table]

Subtotal:  [pnp_subtotal]
Shipping:  [pnp_shipping]
Tax:  [pnp_tax]
Total:  [pnp_card-amount]
