Merchant Order ID: [pnp_order-id]
SalesAgent: [pnp_agent]
Transaction Order ID: [pnp_orderID]

Billing Address:
[pnp_card-name]
[pnp_card-company]
[pnp_card-address1]
[pnp_card-address2]
[pnp_card-city], [pnp_card-state] [pnp_card-zip]
[pnp_card-country]
[pnp_card-prov]

[email_shipping_begin]
Shipping Address:
[pnp_shipname]
[pnp_address1]
[pnp_address2]
[pnp_city],[pnp_state] [pnp_zip]
[pnp_province]
[pnp_country]
[email_shipping_end]

[pnp_email]
[pnp_phone]
[pnp_fax]

[email_purchase_table]

Subtotal:  [pnp_subtotal]
Discount:  [pnp_discnt]
Tax:  [pnp_tax]
Shipping:  [pnp_shipping]
Total:  [pnp_card-amount]

[email_merchant_variables]
