#!/bin/env perl

use lib '/home/pay1/batchfiles/perl_lib';
use lib '/home/pay1/batchfiles/perlpr_lib';

use procutils;

if ( $#ARGV < 0 ) {
  print "       Usage:\n";
  print "         secondary on\n";
  print "         secondary off\n";
  exit;
}

if ( $ARGV[0] eq "off" ) {
  &procutils::flagwrite( "secondary", "paytechsalem2", "/home/pay1/batchfiles/logs/paytechsalem2", "secondary.txt", "unlink", "", "" );
  print "primary paytechsalem2\n";
} elsif ( $ARGV[0] eq "on" ) {
  &procutils::flagwrite( "secondary", "paytechsalem2", "/home/pay1/batchfiles/logs/paytechsalem2", "secondary.txt", "write", "", "1\n" );
  print "secondary paytechsalem2 1\n";
} elsif ( $ARGV[0] eq "1" ) {
  &procutils::flagwrite( "secondary", "paytechsalem2", "/home/pay1/batchfiles/logs/paytechsalem2", "secondary.txt", "write", "", "1\n" );
  print "secondary paytechsalem2 1\n";
} elsif ( $ARGV[0] eq "2" ) {
  &procutils::flagwrite( "secondary", "paytechsalem2", "/home/pay1/batchfiles/logs/paytechsalem2", "secondary.txt", "write", "", "2\n" );
  print "secondary paytechsalem2 2\n";
} elsif ( $ARGV[0] eq "3" ) {
  &procutils::flagwrite( "secondary", "paytechsalem2", "/home/pay1/batchfiles/logs/paytechsalem2", "secondary.txt", "write", "", "3\n" );
  print "secondary paytechsalem2 3\n";
} elsif ( $ARGV[0] eq "4" ) {
  &procutils::flagwrite( "secondary", "paytechsalem2", "/home/pay1/batchfiles/logs/paytechsalem2", "secondary.txt", "write", "", "4\n" );
  print "secondary paytechsalem2 4\n";
}

