package authnet;

sub new {

  %authnet::errorcodes = ('1','This transaction has been approved.'
	,'2','This transaction has been declined.'
	,'3','This transaction has been declined.'	## This code indicates a referral response.
	,'4','This transaction has been declined.' 	## The code returned from the processor indicating that the card used needs to be picked up.
	,'5','A valid amount is required.'		## The value submitted in the amount field did not pass validation for a number.
	,'6','The credit card number is invalid.'
	,'7','The credit card expiration date is invalid.'	## The format of the date submitted was incorrect.
	,'8','The credit card has expired.'
	,'9','This reason code is reserved or not applicable to this API.'
	,'10','This reason code is reserved or not applicable to this API.'
	,'11','A duplicate transaction has been submitted.'	## A transaction with identical amount and credit card information was submitted two minutes prior.
	,'12','An authorization code is required but not present.'	## A transaction that required x_auth_code to be present was submitted without a value.
	,'13','The merchant API login ID is invalid or the account is inactive.'
	,'14','This reason code is reserved or not applicable to this API.'
	,'15','The transaction ID is invalid.'			## The transaction ID value is non-numeric or was not present for a transaction that requires it.
	,'16','The transaction was not found.'
	,'17','The merchant does not accept this type of credit card.'
	,'18','This reason code is reserved or not applicable to this API.'
	,'19','An error occurred during processing. Please try again in 5 minutes.'
	,'20','An error occurred during processing. Please try again in 5 minutes.'
	,'21','An error occurred during processing. Please try again in 5 minutes.'
	,'22','An error occurred during processing. Please try again in 5 minutes.'
	,'23','An error occurred during processing. Please try again in 5 minutes.'
	,'24','This reason code is reserved or not applicable to this API.'
	,'25','An error occurred during processing. Please try again in 5 minutes.'
	,'26','An error occurred during processing. Please try again in 5 minutes.'
	,'27','The transaction resulted in an AVS mismatch. The address provided does not match billing address of cardholder.'
	,'28','The merchant does not accept this type of credit card.'
	,'29','This reason code is reserved or not applicable to this API.'
	,'30','The configuration with the processor is invalid. Call Merchant Service Provider.'
	,'31','This reason code is reserved or not applicable to this API.'
	,'32','This reason code is reserved or not applicable to this API.'
	,'33','FIELD cannot be left blank.'
	,'34','The VITAL identification numbers are incorrect. Call Merchant Service Provider.'
	,'35','An error occurred during processing. Call Merchant Service Provider.'
	,'36','The authorization was approved, but settlement failed.'
	,'37','The credit card number is invalid.'
	,'38','This reason code is reserved or not applicable to this API.'
	,'39','The supplied currency code is either invalid, not supported, not allowed for this merchant or doesn�t have an exchange rate.'
	,'40','This transaction must be encrypted.'
	,'41','This reason code is reserved or not applicable to this API.'
	,'42','This reason code is reserved or not applicable to this API.'
	,'43','This reason code is reserved or not applicable to this API.'
	,'44','This reason code is reserved or not applicable to this API.'
	,'45','This reason code is reserved or not applicable to this API.'
	,'46','This reason code is reserved or not applicable to this API.'
	,'47','The amount requested for settlement may not be greater than the original amount authorized.'
	,'48','This processor does not accept partial reversals.'
	,'49','A transaction amount greater than $[amount] will not be accepted.'
	,'50','This transaction is awaiting settlement and cannot be refunded.'
	,'51','The sum of all credits against this transaction is greater than the original transaction amount.'
	,'52','The transaction was authorized, but the client could not be notified; the transaction will not be settled.'
	,'53','This reason code is reserved or not applicable to this API.'
	,'54','The referenced transaction does not meet the criteria for issuing a credit.'
	,'55','The sum of credits against the referenced transaction would exceed the original debit amount.'
	,'56','This reason code is reserved or not applicable to this API.'
	,'57','An error occurred in processing. Please try again in 5 minutes.'
	,'58','An error occurred in processing. Please try again in 5 minutes.'
	,'59','An error occurred in processing. Please try again in 5 minutes.'
	,'60','An error occurred in processing. Please try again in 5 minutes.'
	,'61','An error occurred in processing. Please try again in 5 minutes.'
	,'62','An error occurred in processing. Please try again in 5 minutes.'
	,'63','An error occurred in processing. Please try again in 5 minutes.'
	,'64','This reason code is reserved or not applicable to this API.'
	,'65','This reason code is reserved or not applicable to this API.'
	,'66','This transaction cannot be accepted for processing.'
	,'67','This reason code is reserved or not applicable to this API.'
	,'68','The version parameter is invalid.'
	,'69','The transaction type is invalid.'
	,'70','The transaction method is invalid.'
	,'71','This reason code is reserved or not applicable to this API.'
	,'72','The authorization code is invalid.'
	,'73','This reason code is reserved or not applicable to this API.'
	,'74','The duty amount is invalid.'
	,'75','The freight amount is invalid.'
	,'76','The tax amount is invalid.'
	,'77','This reason code is reserved or not applicable to this API.'
	,'78','The Card Code (CVV2/CVC2/CID) is invalid.'
	,'79','This reason code is reserved or not applicable to this API.'
	,'80','This reason code is reserved or not applicable to this API.'
	,'81','This reason code is reserved or not applicable to this API.'
	,'82','This reason code is reserved or not applicable to this API.'
	,'83','This reason code is reserved or not applicable to this API.'
	,'84','The device type is invalid.'
	,'85','The market type is invalid.'
	,'86','The response format is invalid.'
	,'87','This market type is not supported.'
	,'88','The Track1 data is invalid.'
	,'89','The Track2 data is invalid.'
	,'90','ACH transactions cannot be processed.'
	,'91','This reason code is reserved or not applicable to this API.'
	,'92','This reason code is reserved or not applicable to this API.'
	,'93','This reason code is reserved or not applicable to this API.'
	,'94','This reason code is reserved or not applicable to this API.'
	,'95','This reason code is reserved or not applicable to this API.'
	,'96','This reason code is reserved or not applicable to this API.'
	,'97','This reason code is reserved or not applicable to this API.'
	,'98','This reason code is reserved or not applicable to this API.'
	,'99','This reason code is reserved or not applicable to this API.'
	,'100','This reason code is reserved or not applicable to this API.'
	,'101','This reason code is reserved or not applicable to this API.'
	,'102','This reason code is reserved or not applicable to this API.'
	,'103','This transaction cannot be accepted.'
	,'104','This reason code is reserved or not applicable to this API.'
	,'105','This reason code is reserved or not applicable to this API.'
	,'106','This reason code is reserved or not applicable to this API.'
	,'107','This reason code is reserved or not applicable to this API.'
	,'108','This reason code is reserved or not applicable to this API.'
	,'109','This reason code is reserved or not applicable to this API.'
	,'110','This reason code is reserved or not applicable to this API.'
	,'111','A valid billing country is required.'
	,'112','A valid billing state/province is required.'
	,'120','An error occurred during processing. Please try again.'
	,'121','An error occurred during processing. Please try again.'
	,'122','An error occurred during processing. Please try again.'
	,'123','This account has not been given the permission(s) required for this request.'
	,'127','The transaction resulted in an AVS mismatch. The address provided does not match billing address of cardholder.'
	,'128','This transaction cannot be processed.'
	,'130','This payment gateway account has been closed.'
	,'131','This transaction cannot be accepted at this time.'
	,'132','This transaction cannot be accepted at this time.'
	,'141','This transaction has been declined.'
	,'145','This transaction has been declined.'
	,'152','The transaction was authorized, but the client could not be notified; the transaction will not be settled.'
	,'165','This transaction has been declined.'
	,'170','An error occurred during processing. Please contact the merchant.'
	,'171','An error occurred during processing. Please contact the merchant.'
	,'172','An error occurred during processing. Please contact the merchant.'
	,'173','An error occurred during processing. Please contact the merchant.'
	,'174','The transaction type is invalid. Please contact the merchant.'
	,'175','The processor does not allow voiding of credits.'
	,'180','An error occurred during processing. Please try again.'
	,'181','An error occurred during processing. Please try again.'
	,'185','This transaction cannot be processed.'
	,'193','This reason code is reserved or not applicable to this API.'
	,'201','This transaction has been declined.'
	,'202','This transaction has been declined.'
	,'203','This transaction has been declined.'
	,'204','This transaction has been declined.'
	,'205','This transaction has been declined.'
	,'206','This transaction has been declined.'
	,'207','This transaction has been declined.'
	,'208','This transaction has been declined.'
	,'209','This transaction has been declined.'
	,'210','This transaction has been declined.'
	,'211','This transaction has been declined.'
	,'212','This transaction has been declined.'
	,'213','This transaction has been declined.'
	,'214','This transaction has been declined.'
	,'215','This transaction has been declined.'
	,'216','This transaction has been declined.'
	,'217','This transaction has been declined.'
	,'218','This transaction has been declined.'
	,'219','This transaction has been declined.'
	,'220','This transaction has been declined.'
	,'221','This transaction has been declined.'
	,'222','This transaction has been declined.'
	,'223','This transaction has been declined.'
	,'224','This transaction has been declined.'
	,'270','The line item [item number] is invalid.'
	,'271','The number of line items submitted is not allowed. A maximum of 30 line items can be submitted.'
	,'315','The credit card number is invalid.'
	,'316','The credit card expiration date is invalid.'
	,'317','The credit card has expired.'
	,'318','A duplicate transaction has been submitted.'
	,'319','The transaction cannot be found.');

  %authnet::testprocessor_map = ('00','1','200','2','XX','3','215','4','211','5','303','5','304','5','305','5','306','6','307','6','308','6','310','6','205','8');

  %authnet::pnp_map = ('P55','6','P57','P01','27','P49','28','P56','78','P76','11');

  %authnet::paytechtampa_map = ('00','1','200','2','XX','3','215','4','211','5','303','5','304','5','305','5','306','6','307','6','308','6','310','6','205','8');

  %authnet::moneris_map = ('000','1','002','1','003','1','004','1','005','1','006','1'.'007','1','008','1','009','1','010','1','011','1','012','1','013','1','014','1','015','1','016','1','017','1','018','1','019','1','020','1','021','1','022','1','023','1','024','1','025','1','026','1','027','1','028','1','029','1','030','1','031','1','032','1','033','1','034','1','035','1','036','1','037','1','038','1','039','1','040','1','041','1','042','1','043','1','044','1','045','1','046','1','047','1','048','1','049','1');


  #%authnet::moneris_map = (000','1','00','1','02','1', '200','2','XX','3','215','4','211','5','303','5','304','5','305','5','306','6','307','6','308','6','310','6','205','8');

}



1;

